config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  
  get 'static_pages/home'

  get 'courts/new'
  get 'courts/create'
  get 'courts/destroy'
  
  get 'sessions/new'

  get 'anotados/index'
  get 'anotados/create'
  get 'anotados/new'
  get 'anotados/show'
  post 'anotados/aceptar'
  post 'anotados/quitar'

  get 'partidos/index'
  get 'partidos/show'
  get 'partidos/new'
  get 'partidos/create'

  get '/signup',  to: 'users#new'  
  get '/login',   to: 'sessions#new'
  get 'logout',   to: 'sessions#destroy'
  post  '/login', to: 'sessions#create'
  # get 'locals/canchas' to: 'locals#canchas'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :partidos do
    member do
      get :armar
    end
  end
  resources :anotados
  resources :relationships,  only: [:create, :destroy]
  
  resources :locals do
    member do
      get :canchas
    end
  end
  resources :courts, only: [:new, :create, :destroy]
end

app/models/anotado.rb
class Anotado < ApplicationRecord
	belongs_to :user
	belongs_to :partido
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/court.rb
class Court < ApplicationRecord
  belongs_to :local
end

app/models/court_type.rb
class CourtType < ActiveRecord::Base
  enum court_type: [:F5, :F7, :F11]
end

app/models/local.rb
class Local < ApplicationRecord
	has_many :courts
	belongs_to :user 
end

app/models/partido.rb
class Partido < ApplicationRecord
  NUMBER_OF_MAX_PLAYERS_SUBSCRIBED = 10
  belongs_to :user
  belongs_to :local
  has_many :anotados
  has_many :aceptados, -> {where(aceptado: true)}, :class_name => 'Anotado' #, before_add: :validates_players_limit

  
  private

  def validates_players_limit(aceptados)
  	raise Exception.new if aceptados.size >= NUMBER_OF_MAX_PLAYERS_SUBSCRIBED
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"

	validates :follower_id, presence: true
	validates :followed_id, presence: true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :court
  belongs_to :partido
end

app/models/user.rb
class User < ApplicationRecord
	#roles
	enum role: [:local_owner, :player]
	after_initialize :set_default_role, :if => :new_record?

	has_secure_password
	#relaciones con los partidos
	has_many :partidos #organiza muchos partidos
	has_many :anotados
	has_many :anotado_a, through: :anotados, source: :partido
	
	#relaciones con los usuarios
	has_many :active_relationships, class_name: "Relationship",
																foreign_key: "follower_id",
																dependent: :destroy
	has_many :passive_relationships, class_name:  "Relationship",
                                 foreign_key: "followed_id",
                                 dependent:   :destroy
	has_many :following, through: :active_relationships, source: :followed
	has_many :followers, through: :passive_relationships, source: :follower 


	before_save { self.nick = nick.downcase }
	validates :nick, 	presence: true, 
									 	length: {minimum: 5}, 		
									 	uniqueness: {case_sensitive: false}
	validates :password, presence: true,
											 length: { minimum: 6 }
	validates :email, presence: true,
										format: { with: /\A\w[\w\d]+@\w+.com/ },
										uniqueness: true
	validates :nombre, presence: true
	validates :apellido, presence: true
	validates :nacimiento, presence: true

	#imagenes
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/default_user.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

	#seguir usuarios

	def follow (other_user)
		following << other_user
	end

	def unfollow (other_user)
		following.delete(other_user)
	end

	def following?(other_user)
		following.include?(other_user)
	end

	#roles
	def set_default_role
    self.role ||= :player
  end

	private


end

app/controllers/anotados_controller.rb
class AnotadosController < ApplicationController

  def index
  end

  def show
    @anotado = Anotado.find(params[:id])
  end

	def new
    matches = Partido.all
    anotados = current_user.anotado_a.to_a
    @partidos = matches.to_a
    @partidos.delete_if {|partido| anotados.include?(partido)}
    @anotado = Anotado.new
  end

  def create
  	@anotado = Anotado.new(anotado_params)
  	if (@anotado.save)
  		redirect_to Partido.find(@anotado.partido_id)
		else
      render 'shared/error_messages' 
		end
  end


  def aceptar
    anotado = Anotado.find_by!(user_id: params[:user_id], partido_id: params[:partido_id])
    anotado.aceptado = true
    anotado.save
    redirect_to Partido.find(params[:partido_id])
  end

  def quitar
    anotado = Anotado.find_by!(user_id: params[:user_id], partido_id: params[:partido_id])
    anotado.aceptado = false
    anotado.save
    redirect_to Partido.find(params[:partido_id])
  end

  private

  def anotado_params
  	params.require(:anotado).permit(:user_id, :partido_id)
  end
end

app/controllers/courts_controller.rb
class CourtsController < ApplicationController
  def new
  end

  def create
    # debugger
    courts_number = params[:courts_number]
    if courts_number == 0
      @court = Court.new(court_params)
      @court.save  
    else
      params[:courts_number].to_i.times do |i|
        @court = Court.new(court_params)
        @court.save  
      end
    end
  
  	
		redirect_to Local.find(court_params[:local_id])

  end

  def destroy
  end

  private

  def court_params
  	params.require(:court).permit(:local_id, :precio, :court_type)
  end
end

app/controllers/locals_controller.rb
class LocalsController < ApplicationController

	before_action :require_owner_login, only: [:new, :create, :edit, :update, :destroy]

	def index
		@locals = Local.all
	end

	def new
		@local = Local.new
	end

	def create
		@local = Local.new(local_params)
		@court = Court.new
		if @local.save
			render 'show'
		else
			render 'new'
		end
	end

	def show
		@local = Local.find(params[:id])
		@partidos = Partido.where("local_id = ?", @local.id)
		@court = Court.new
	end

	def edit
		@local = Local.find(params[:id])
	end

	def update
		@local = Local.find(params[:id])
		if @local.update_attributes(local_params)
			render 'show'
		else
			render 'edit'
		end
	end

	def canchas
		@local = Local.find(params[:id])
		@canchas = @local.courts.length
		# debugger
		render :partial => 'canchas'
	end

	def destroy
	end

	private

		def local_params
			params.require(:local).permit(:nombre, :barrio, :direccion, :telefono, :email,
																		:opens, :closes, :user_id)
		end

		def require_owner_login
			unless logged_in?
        flash[:error] = "You must be logged in to access this section"
        redirect_to '/login'
        return
      end
      if current_user.player?
        render 'static_pages/error_tipo_usuario'
      end
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		if logged_in? and current_user.player?	
				@users = User.player
		else
			@users = User.all
		end
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def edit
	end

	def create
		@user = User.new(user_params)
		if(@user.save)
			log_in @user
			redirect_to :action => 'show', :id => @user.id
		else
			render 'new'
		end
	end

	def update
	end

	def destroy
		
	end
	

	private
		
		def user_params
			params.require(:user).permit(	:nick, :password, 
																		:password_confirmation, 
																 		:nombre, :apellido, :nacimiento, :email, 
																 		:descripcion, :avatar, :role)
		end

end

app/helpers/anotados_helper.rb
module AnotadosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courts_helper.rb
module CourtsHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/partidos_helper.rb
module PartidosHelper
end

app/helpers/ralationships_helper.rb
module RalationshipsHelper
end

app/helpers/reservation_helper.rb
module ReservationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def current_user?(other_user)
		@current_user.id == other_user.id
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/anotados/create.html.erb
<h1>Anotados#create</h1>
<p>Find me in app/views/anotados/create.html.erb</p>

app/views/anotados/index.html.erb
<h1>Anotados#index</h1>
<p>Find me in app/views/anotados/index.html.erb</p>

app/views/anotados/new.html.erb
<!-- NO SE UTILIZA MAS -->
<div class="row">

	<h3 class="center z-depth-3 grey">Anotarse a un partido</h3>

	<table class="responsive-table bordered white z-depth-3">
		<thead>
			<th>Lugar</th>
			<th>Fecha</th>
		</thead>

		<tbody>
			<% @partidos.each do |partido| %>
				<tr> 
					<td><%= partido.lugar %></td>
					<td><%= partido.fecha %></td>
				
					<td>
					<%= form_for (@anotado) do |f| %>

						<%= f.hidden_field :user_id, :value => current_user.id %>

						<%= f.hidden_field :partido_id, :value => partido.id %>

						<%= f.submit 'Anotarse', :class=>"btn" %>

					<% end %>
					</td>
				</tr>	
			<%end%>
		</tbody>
	</table>
</div>

app/views/anotados/show.html.erb
<%redirect_to Partido.find(@anotado.partido_id)%>

app/views/locals/_canchas.html.erb
<% if @local %>	
	<div class ="input-field" >
		<%= label_tag "partido[court_id]", "Cancha" %>
		<%= number_field_tag "partido[court_id]", 1, min: 1, max: @canchas %>
	</div>
<%end%>

app/views/locals/edit.html.erb
<h3 class="center">Editar Local</h3>

<div class="card white">
<%= form_for @local do |f| %>

	
	<div class="card-content">
			
		<%= f.label :nombre %>
		<div class="input-field" >
			<%= f.text_field :nombre %>
		</div>	

		<%= f.label :barrio %>
		<div class="input-field" >
			<%= f.text_field :barrio %>
		</div>
		
		<%= f.label :direccion %>
		<div class="input-field">			
			<%= f.text_field :direccion %>
		</div>

		<%= f.label :telefono %>
		<div class="input-field">
			<%= f.text_field :telefono %>
		</div>

		<%= f.label :email %>
		<div class="input-field">
			<%= f.email_field :email %> 
		</div>

		<%= f.label :opens %>
		<div class="input-field">
			<%= f.text_field :opens %>
		</div>

		<%= f.label :closes %>
		<div class="input-field">
			<%= f.text_field :closes %>
		</div>

	</div>


	<div class="card-action">
		<%= f.submit "Editar Local", :class=>"btn" %>
	</div>
	
<% end %>
</div>

app/views/locals/index.html.erb
<div class="row">
	<h3 class="responsive-table center z-depth-2 grey">Lista de Locales</h3>

	<table class="white z-depth-2">
		<thead> 
			<th> Nombre </th>
			<th> Direccion </th>
			<th> Telefono </th>
		</thead>

		<tbody >
			<% if @locals.empty? %>
				<tr> <td> <span> No existen locales <span> </td></tr>
			<%else%>
				<% @locals.each do |local| %>
					<tr> 
						<td> <%= local.nombre	%></td>
						<td> <%= local.direccion %></td>
						<td> <%= local.telefono %></td>
						<td> <%= link_to 'Ver Local', local, :class=>"btn" 		%></td>
					</tr>
				<% end %>
			<%end%>
		</tbody>
</table>
</div>

app/views/locals/new.html.erb
<h3 class="center">Crear Local</h3>

<div class="row white z-depth-3"  >
	<div class="col s12">
		<%= form_for @local do |f| %>
		
			<%= f.hidden_field :user_id, :value => current_user.id %>

			<div class="input-field" >
				<%= f.label :nombre %>
				<%= f.text_field :nombre %>
			</div>

			<div class="input-field" >
				<%= f.label :barrio %>
				<%= f.text_field :barrio %>
			</div>
			
			<div class="input-field">
				<%= f.label :direccion %>
				<%= f.text_field :direccion %>
			</div>

			<div class="input-field">
				<%= f.label :telefono %>
				<%= f.text_field :telefono %>
			</div>

			<div class="input-field">
				<%= f.label :email %>
				<%= f.email_field :email %> 
			</div>

			<div class="row">
				<div class="input-field col s6">
					<%= f.label :opens, "Abre" %>
					<%= f.text_field :opens %>
				</div>

				<div class="input-field col s6">
					<%= f.label :closes, "Cierra" %>
					<%= f.text_field :closes %>
				</div>

			</div>

			<%= f.submit "Crear Local", :class=>"btn" %>

		<% end %>
	</div>
</div>

app/views/locals/show.html.erb
<div class="row">
	<h3 class="center z-depth-2 grey">Datos de Local</h3>

	<table class="centered highlight white z-depth-2" style="margin-bottom: 25px">
		
			<tbody>
				<tr>
					<td> Cancha</td> <td> <%= @local.nombre %> </td>
				</tr>
				<tr>
					<td> Barrio</td> <td> <%= @local.barrio %> </td>
				</tr>
				<tr>
					<td> Direccion</td> <td> <%= @local.direccion %> </td>
				</tr>
				<tr>
					<td> Telefono</td> <td><%= @local.telefono %> </td>
				</tr>
				<tr>
					<td> Email</td> <td><%= @local.email %> </td>
				</tr>
				<tr>
					<td> Abierto</td> <td> <%= @local.opens.strftime("%H:%M") %>Hs - <%= @local.closes.strftime("%H:%M") %>Hs</td>
				</tr>
				
			</tbody>
	</table>

	<% if logged_in? and current_user?(User.find(@local.user_id)) %>
		<div class="center" style="margin-bottom: 20px">
			<%= link_to 'Editar Datos Local', edit_local_path(@local), :class=>'btn-large' %>
		</div>
	

		<div class="row">
			<div class="col s6">
				<div class="card z-depth-3">
					<div class="card-content">
						<span class="card-title"> Crear Cancha </span>
						<%= form_for (@court) do |f| %>
							
							<%= f.hidden_field :local_id, :value => @local.id %>
							
							<div class="input-field">
								<%= f.label :precio %>
								<%= f.text_field :precio %>
							</div>

							<div class="input-field">
							  <%= f.select :court_type, CourtType.court_types.keys %>
							  <label>Tipo de Cancha</label>
							</div>

							<div class="input-field">
								<%= number_field_tag :courts_number, "Cantidad de canchas", in: 1...15%>
								<label>Cantidad</label>
							</div>

							<div class="card-action">
								<%= f.submit "Crear Cancha", :class =>"btn" %>
							</div>
						<%end%>
					</div>
				</div>
			</div>
		<%end%>

		<div class="col s6">
			<div class="card z-depth-3">
				<div class="card-content">
					<span class="card-title"> Lista Canchas </span>
					<ul class="collection">
						<% @local.courts.each do |court| %>
							<table class="bordered centered">
								<thead>
									<th> Numero </th>
									<th> Precio </th>
									<th> Tipo </th>
								</thead>
								<tbody>
									<td> <%= court.id %> </td>
									<td> $<%= court.precio %> </td>
									<td> <%= court.court_type %> </td>
								</tbody>
							</table>
							
						<% end %>
					</ul>
				</div>
				<div class="card-action">
					
				</div>
			</div>
		</div>

		<!-- Mostrar partidos para la cancha -->
		<div class="col s12">
			<div class="card z-depth-3">
				<div class="card-content">
					<span class="card-title">Lista Partidos</span>
					<table>
						<thead>
							<th>Organizador</th>
							<th>Fecha</th>
							<th>Hora</th>
							<th>Cancha</th>
						</thead>
						<% @partidos.each do |partido|%>		
							<tbody>
								<td> <%= partido.user.nick %> </td>
								<td> <%= partido.fecha.strftime("%d/%m/%y")%> </td>
								<td> <%= partido.fecha.strftime("%H:%M")%> </td>
								<td> <%= partido.court_id%> </td>
								<!-- <td> <%= link_to "ver partido", partido_path(partido), :class=>"btn"%> </td> -->
							</tbody>
						<%end%>
					</table>
				</div>
				<div class="card-action">
					<%= link_to "Crear Partido", new_partido_path, :class => "btn" %>
				</div>
			</div>
			
		</div>
	</div>

</div>