config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  
  get 'static_pages/home'

  get 'courts/new'
  get 'courts/create'
  get 'courts/destroy'
  
  get 'sessions/new'

  get 'anotados/index'
  get 'anotados/create'
  get 'anotados/new'
  get 'anotados/show'
  post 'anotados/aceptar'
  post 'anotados/quitar'

  get 'partidos/index'
  get 'partidos/show'
  get 'partidos/new'
  get 'partidos/create'

  get '/signup',  to: 'users#new'  
  get '/login',   to: 'sessions#new'
  get 'logout',   to: 'sessions#destroy'
  post  '/login', to: 'sessions#create'
  # get 'locals/canchas' to: 'locals#canchas'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :partidos do
    member do
      get :armar
    end
  end
  resources :anotados
  resources :relationships,  only: [:create, :destroy]
  
  resources :locals do
    member do
      get :canchas
    end
  end
  resources :courts, only: [:new, :create, :destroy]
end

app/models/partido.rb
class Partido < ApplicationRecord
  NUMBER_OF_MAX_PLAYERS_SUBSCRIBED = 10
  belongs_to :user
  belongs_to :local
  has_many :anotados
  has_many :aceptados, -> {where(aceptado: true)}, :class_name => 'Anotado' #, before_add: :validates_players_limit

  
  private

  def validates_players_limit(aceptados)
  	raise Exception.new if aceptados.size >= NUMBER_OF_MAX_PLAYERS_SUBSCRIBED
  end
end

app/controllers/partidos_controller.rb
class PartidosController < ApplicationController
  
  before_action :require_player_login, only: [:new, :create]

  def index
  	todos = Partido.all
    @partidos = []
     
    if logged_in?
      todos.each do |partido|
        
        if current_user.following.pluck(:id).include?(partido.user_id) 
          #hacer esto sin que consulte a la base para encontrar el usuario
          @partidos << partido
        end
      end
    else
      @partidos = todos
    end

  end

  def show
    @partido = Partido.find(params[:id])
    @local = Local.find(@partido.local_id)
    @anotado = nil
    unless @partido.anotados.include?(Anotado.find_by({partido_id: @partido.id, user_id: current_user.id}))
      @anotado = Anotado.new
    end
  end

  def new
  	@partido = Partido.new
    @locals = Local.all.pluck(:id, :nombre)
  end

  def create
    fecha = DateTime.new(partido_params["fecha(1i)"].to_i, partido_params["fecha(2i)"].to_i,
                        partido_params["fecha(3i)"].to_i, partido_params["fecha(4i)"].to_i,0,0)
    if fecha >= Date.today
      local_id = partido_params[:local_id]
      court_id = partido_params[:court_id]
    
      @error_fecha = false
      @partido = Partido.new
      @locals = Local.all.pluck(:id, :nombre)

      
      @user = User.find(partido_params[:user_id])
      @partido = @user.partidos.build(partido_params)
      if(@partido.save)
        Anotado.create(user_id: @user.id, partido_id: @partido.id)
        render 'show'
      else
        @error_fecha = true
        render 'new'
      end
    else
      @partido = Partido.new
      @locals = Local.all.pluck(:id, :nombre)
      @error_fecha = true;
      render 'new'
    end
  end

  def armar
    partido = Partido.find(params[:id])
    @equipo1 = Array.new
    @equipo2 = Array.new
    
    if partido.aceptados.length == 10
      for i in 0..4
        @equipo1 << partido.aceptados[i]
      end 
      for i in 5..9
        @equipo2 << partido.aceptados[i]
      end
    else
      @error_cant_aceptados = true
    end

    respond_to do |format|
      format.html
      format.js 
    end
  end
  private
  	def partido_params
  		params.require(:partido).permit(:user_id, :local_id, :court_id, :fecha)
  	end

    def require_player_login
      unless logged_in?
        flash[:error] = "You must be logged in to access this section"
        redirect_to '/login'
        return
      end
      if current_user.local_owner?
        render 'static_pages/error_tipo_usuario'
      end
    end
end

app/helpers/partidos_helper.rb
module PartidosHelper
end

app/views/partidos/_armar.html.erb
<h4 class="center z-depth-2 grey" style="padding: 10px">Equipos armados</h4>
<div class="col s6">
		<ul class="collection with-header z-depth-2">
			<li class="collection-header grey"> <h5> Equipo 1 </h5> </li>
			<% @equipo1.each do |anotado| %>
				<li class="collection-item"> <%= anotado.user_id %> </li>
			<%end%>
		</ul>
</div>	

<div class="col s6">
	<ul class="collection with-header z-depth-2">
		<li class="collection-header grey"> <h5> Equipo 2 </h5> </li>
		<% @equipo2.each do |anotado| %>
			<li class="collection-item"> <%= anotado.user_id %> </li>
		<%end%>
	</ul>
</div>

app/views/partidos/_equipos.html.erb
<div class="col s6">
		<ul class="collection with-header z-depth-2">
			<li class="collection-header grey"> <h5> Equipo 1 </h5> </li>
			
		</ul>
</div>	

<div class="col s6">
	<ul class="collection with-header z-depth-2">
		<li class="collection-header grey"> <h5> Equipo 2 </h5> </li>
	</ul>
</div>

app/views/partidos/armar.js.erb
$('#equipos').html( '<%= j render("armar") %>');

app/views/partidos/create.html.erb
<h1>Partidos#create</h1>
<p>Find me in app/views/partidos/create.html.erb</p>

app/views/partidos/index.html.erb
<div class="row">
	<h3 class="responsive-table center z-depth-2 grey">Lista de Partidos</h3>

	<table class="white z-depth-2">
		<thead> 
			<th> Nick Organizador </th>
			<th> Lugar </th>
			<th> Cancha </th>
			<th> Fecha </th>
			<th> Hora </th>
		</thead>

		<tbody >
			<% if @partidos.empty? %>
				<tr> <td> <span> No hay partidos para este usuario <span> </td></tr>
			<%else%>
				<% @partidos.each do |partido| %>
					<tr> 
						<td> <%= link_to partido.user.nick, partido.user 	%></td>
						<td> <%=  #esto hace muchas consultas
									partido.local.nombre %></td> 
						<td> <%= partido.court_id %></td>
						<td> <%= partido.fecha.strftime("%d/%m/%y") %></td>
						<td> <%= partido.fecha.strftime("%H:%M") %></td>
						<td> <%= link_to 'Ver Partido', partido, :class=>"btn" 		%></td>
					</tr>
				<% end %>
			<%end%>
		</tbody>
</table>
</div>

app/views/partidos/new.html.erb
<% if @error_fecha %>
	<%= render :partial => 'static_pages/error_fecha' %>
	<% @error_fecha = false %>
<%end%>
<div class="card white">
	<div class="card-content">
		<span class="card-title center">Crear Partido</span>

	
		<%= form_for @partido do |f| %>
			
			<%= f.hidden_field :user_id, :value => current_user.id %>

			<div class="input-field">
				<%= f.select :local_id,  {:onchange => "change_on_select(this.options[this.selectedIndex].value);" } do %>
					<% @locals.each do |local| %>
						<%= content_tag(:option, local.last, value: local.first) %>
					<%end%>
				<%end%>
				<label>Seleccionar Local</label>
			</div>
			<div id="canchas">
				
			</div>
			
			<%= f.label :fecha %>
			<div class="input-field">
				<%= f.datetime_select :fecha, discard_minute: true, start_year: Date.today.year, end_year: Date.today.year, default: Date.today %>	
			</div>

			<div class="card-action">
				<%= f.submit 'Crear Partido', :class=>"btn" %>
			</div>
		<% end %>
	</div>
</div>

<script type="text/javascript"> 


	$(document).ready(function(){
		$('#partido_local_id').change(function(){
			var local_id = $('#partido_local_id').val();
			$.get('/locals/'+ local_id +'/canchas', function(data, status){
			if(status === 'success'){
				// console.log(status);
				$('#canchas').html(data);
			}
			
			});
		});
	});
	
</script>

app/views/partidos/show.html.erb
<div class="row" style="margin-top: 50px">
	<h3 class="center z-depth-2 grey">Datos de Partido</h3>

	<table class="bordered highlight white z-depth-2" style="margin-bottom: 25px">
			<tbody>
				<tr>
					<td> ID Partido</td>
					<td id="partido_id"> <%= @partido.id %>  </td>
				</tr>
				<tr>	
					<td> ID Creador</td>		
					<td> <%= @partido.user_id %>  </td>
				</tr>
				<tr>
					<td> Organizador</td>
					<td> <%= link_to @partido.user.nick, @partido.user %>  </td>
				</tr>
				<tr>
					<td>Lugar</td>
					<td> <%= link_to @local.nombre, @local %>  </td>
				</tr>
				<tr>
					<td>Cancha</td>
					<td> <%= @partido.court_id %>  </td>
				</tr>
				<tr>
					<td>Fecha</td>
					<td> <%= @partido.fecha.strftime("%d/%m/%y") %> </td>
				</tr>
				<tr>
					<td>Hora</td>
					<td> <%= @partido.fecha.strftime("%H:%M") %> </td>
				</tr>
			</tbody>
	</table>
</div>
		
<div class="row">

	<% unless @anotado == nil %>
		<div class="col s12 center" style = "margin-bottom: 50px">
			<%= form_for (@anotado) do |f| %>

				<%= f.hidden_field :user_id, :value => current_user.id %>

				<%= f.hidden_field :partido_id, :value => @partido.id %>

				<%= f.submit 'Anotarse', :class=>"btn-large" %>

			<% end %>

		</div>
	<%end%>

	<div class="col s6">
		<ul class="collection with-header z-depth-2">
			<li class="collection-header grey"><h5>Usuarios Anotados</h5></li>
			<% @partido.anotados.each do |anotado| %>
				<li class="collection-item">
					<% user_anotado = User.find(anotado.user_id) %>
					<%= link_to user_anotado.nick, user_anotado %>
					
					<% if current_user?(@partido.user) and 
						not @partido.aceptados.include?(Anotado.find(anotado.id))  %>
							<%= form_tag anotados_aceptar_path do %>
								<%= hidden_field_tag :user_id, anotado.user_id %>
								<%= hidden_field_tag :partido_id, @partido.id %>
								<%= submit_tag 'Aceptar', :class => "btn" %>
							<%end%>
						<%end%>
					<end%>
				</li>
			<%end%>
		</ul>	
	</div>

	<div class="col s6">
		<ul class="collection with-header z-depth-2">
			<li class="collection-header grey"><h5>Usuarios Aceptados</h5></li>
			<% @partido.aceptados.each do |aceptado| %>
			<% user_aceptado = User.find(aceptado.user_id) %>
				<li class="collection-item"> <%= link_to user_aceptado.nick, user_aceptado %> 

					<% if current_user.id == aceptado.user_id or 
						current_user?(@partido.user) then %>
						<%= form_tag anotados_quitar_path do %>
							<%= hidden_field_tag :user_id, aceptado.user_id %>
							<%= hidden_field_tag :partido_id, @partido.id %>
							<%= submit_tag 'Borrar', :class => "btn" %>
						<%end%>
					<%end%>
				</li>
			<%end%>
		</ul>
	</div>
</div>

<% if @partido.aceptados.length == 10 and current_user?(@partido.user) %>
	<div class="row">
		<div class="center" style="margin-bottom: 20px">
			<%= form_tag "/partidos/"+@partido.id.to_s+"/armar", method: 'get', remote: true do %>
				<%= submit_tag "Armar Equipos", :class => "btn-large" %>
			<%end%>
		</div>
	</div>
<%end%>

<div id="equipos" class="row">
	
</div>	