config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  
  get 'static_pages/home'

  get 'courts/new'
  get 'courts/create'
  get 'courts/destroy'
  
  get 'sessions/new'

  get 'anotados/index'
  get 'anotados/create'
  get 'anotados/new'
  get 'anotados/show'
  post 'anotados/aceptar'
  post 'anotados/quitar'

  get 'partidos/index'
  get 'partidos/show'
  get 'partidos/new'
  get 'partidos/create'

  get '/signup',  to: 'users#new'  
  get '/login',   to: 'sessions#new'
  get 'logout',   to: 'sessions#destroy'
  post  '/login', to: 'sessions#create'
  # get 'locals/canchas' to: 'locals#canchas'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :partidos do
    member do
      get :armar
    end
  end
  resources :anotados
  resources :relationships,  only: [:create, :destroy]
  
  resources :locals do
    member do
      get :canchas
    end
  end
  resources :courts, only: [:new, :create, :destroy]
end

app/models/anotado.rb
class Anotado < ApplicationRecord
	belongs_to :user
	belongs_to :partido
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/court.rb
class Court < ApplicationRecord
  belongs_to :local
end

app/models/court_type.rb
class CourtType < ActiveRecord::Base
  enum court_type: [:F5, :F7, :F11]
end

app/models/local.rb
class Local < ApplicationRecord
	has_many :courts
	belongs_to :user 
end

app/models/partido.rb
class Partido < ApplicationRecord
  NUMBER_OF_MAX_PLAYERS_SUBSCRIBED = 10
  belongs_to :user
  belongs_to :local
  has_many :anotados
  has_many :aceptados, -> {where(aceptado: true)}, :class_name => 'Anotado' #, before_add: :validates_players_limit

  
  private

  def validates_players_limit(aceptados)
  	raise Exception.new if aceptados.size >= NUMBER_OF_MAX_PLAYERS_SUBSCRIBED
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"

	validates :follower_id, presence: true
	validates :followed_id, presence: true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :court
  belongs_to :partido
end

app/models/user.rb
class User < ApplicationRecord
	#roles
	enum role: [:local_owner, :player]
	after_initialize :set_default_role, :if => :new_record?

	has_secure_password
	#relaciones con los partidos
	has_many :partidos #organiza muchos partidos
	has_many :anotados
	has_many :anotado_a, through: :anotados, source: :partido
	
	#relaciones con los usuarios
	has_many :active_relationships, class_name: "Relationship",
																foreign_key: "follower_id",
																dependent: :destroy
	has_many :passive_relationships, class_name:  "Relationship",
                                 foreign_key: "followed_id",
                                 dependent:   :destroy
	has_many :following, through: :active_relationships, source: :followed
	has_many :followers, through: :passive_relationships, source: :follower 


	before_save { self.nick = nick.downcase }
	validates :nick, 	presence: true, 
									 	length: {minimum: 5}, 		
									 	uniqueness: {case_sensitive: false}
	validates :password, presence: true,
											 length: { minimum: 6 }
	validates :email, presence: true,
										format: { with: /\A\w[\w\d]+@\w+.com/ },
										uniqueness: true
	validates :nombre, presence: true
	validates :apellido, presence: true
	validates :nacimiento, presence: true

	#imagenes
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/default_user.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

	#seguir usuarios

	def follow (other_user)
		following << other_user
	end

	def unfollow (other_user)
		following.delete(other_user)
	end

	def following?(other_user)
		following.include?(other_user)
	end

	#roles
	def set_default_role
    self.role ||= :player
  end

	private


end

app/controllers/courts_controller.rb
class CourtsController < ApplicationController
  def new
  end

  def create
    # debugger
    courts_number = params[:courts_number]
    if courts_number == 0
      @court = Court.new(court_params)
      @court.save  
    else
      params[:courts_number].to_i.times do |i|
        @court = Court.new(court_params)
        @court.save  
      end
    end
  
  	
		redirect_to Local.find(court_params[:local_id])

  end

  def destroy
  end

  private

  def court_params
  	params.require(:court).permit(:local_id, :precio, :court_type)
  end
end

app/controllers/locals_controller.rb
class LocalsController < ApplicationController

	before_action :require_owner_login, only: [:new, :create, :edit, :update, :destroy]

	def index
		@locals = Local.all
	end

	def new
		@local = Local.new
	end

	def create
		@local = Local.new(local_params)
		@court = Court.new
		if @local.save
			render 'show'
		else
			render 'new'
		end
	end

	def show
		@local = Local.find(params[:id])
		@partidos = Partido.where("local_id = ?", @local.id)
		@court = Court.new
	end

	def edit
		@local = Local.find(params[:id])
	end

	def update
		@local = Local.find(params[:id])
		if @local.update_attributes(local_params)
			render 'show'
		else
			render 'edit'
		end
	end

	def canchas
		@local = Local.find(params[:id])
		@canchas = @local.courts.length
		# debugger
		render :partial => 'canchas'
	end

	def destroy
	end

	private

		def local_params
			params.require(:local).permit(:nombre, :barrio, :direccion, :telefono, :email,
																		:opens, :closes, :user_id)
		end

		def require_owner_login
			unless logged_in?
        flash[:error] = "You must be logged in to access this section"
        redirect_to '/login'
        return
      end
      if current_user.player?
        render 'static_pages/error_tipo_usuario'
      end
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		if logged_in? and current_user.player?	
				@users = User.player
		else
			@users = User.all
		end
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def edit
	end

	def create
		@user = User.new(user_params)
		if(@user.save)
			log_in @user
			redirect_to :action => 'show', :id => @user.id
		else
			render 'new'
		end
	end

	def update
	end

	def destroy
		
	end
	

	private
		
		def user_params
			params.require(:user).permit(	:nick, :password, 
																		:password_confirmation, 
																 		:nombre, :apellido, :nacimiento, :email, 
																 		:descripcion, :avatar, :role)
		end

end

app/helpers/anotados_helper.rb
module AnotadosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courts_helper.rb
module CourtsHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/partidos_helper.rb
module PartidosHelper
end

app/helpers/ralationships_helper.rb
module RalationshipsHelper
end

app/helpers/reservation_helper.rb
module ReservationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def current_user?(other_user)
		@current_user.id == other_user.id
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/users/index.html.erb
<h3 class="center grey z-depth-2">Lista de Usuarios</h3>

<ul class="collection z-depth-2">
	<% @users.each  do |user| %>
		<li class="collection-item avatar">
			<%= image_tag user.avatar.url, height: '32', width: '32', :class=>"circle" %> 
			<span class="title">Nickname: <%= link_to user.nick, user %>  </span> 
	   	<p> <%= user.nombre %>, <%= user.apellido %> </p>
		</li>
	<% end %>
</ul>

app/views/users/new.html.erb
<h3 class="center">Crear Usuario</h3>

<div class="card white">
<%= form_for @user, html: { multipart: true } do |f| %>

	<%= render 'shared/error_messages'%>
	
	<div class="card-content">
		<div class="input-field" >
			<%= f.label :nick %>
			<%= f.text_field :nick %>
		</div>
		
		<div class="input-field">
			<%= f.label :password %>
			<%= f.password_field :password %>
		</div>

		<div class="input-field">
			<%= f.label :password_confirmation %>
			<%= f.password_field :password_confirmation %>
		</div>

		<div class="input-field">
			<%= f.label :email %>
			<%= f.email_field :email %> 
		</div>

		<div class="input-field">
			<%= f.label :nombre %>
			<%= f.text_field :nombre %>
		</div>
		<div class="input-field">
			<%= f.label :apellido %>
			<%= f.text_field :apellido %>
		</div>
		<%= f.label "Fecha Nacimiento" %>
		<div class="input-field">			
			<%= f.date_field :nacimiento %>
		</div>
		<div class="input-field">
			<%= f.label :descripcion %>
			<%= f.text_area :descripcion %>
		</div>
		
		<div class="input-field">
			<%= f.select :role, User.roles.keys %>
		</div>
		
		<%= f.label "Imagen Perfil" %>
		<div class="input-field file-field">
			<div class="btn">
				<span>FILE</span>
				<%= f.file_field :avatar	 %>	
			</div>
			
			<div class="file-path-wrapper">
				<input class="file-path validate" type="text">
			</div>				
		</div>

	</div>


	<div class="card-action">
		<%= f.submit "Crear Usuario", :class=>"btn" %>
	</div>
	
<% end %>
</div>

app/views/users/show.html.erb
<div class="row">
<h3 class="center z-depth-2 grey">Datos de Usuario</h3>

<table class="centered highlight white z-depth-2" style="margin-bottom: 25px">
	
		<tbody>
			<tr>
				<td> Nickname</td> <td> <%= @user.nick %> </td>
			</tr>
			<tr>
				<!-- <img src="/assets/default_user.png" alt="imagen" class="circle" height="42" width="42"> -->
				<td> <%= image_tag @user.avatar.url, height: '32', width: '32', :class => "circle" %>  </td> 

				<td>
					<% if logged_in? %>
	   		<% unless current_user?(@user) %>
	   			<% if current_user.following?(@user) %>
	   				<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
 							<%= f.submit "Unfollow", class: "btn" %>
						<% end %>
					<% else %>
	   				<%= form_for(current_user.active_relationships.build) do |f| %>
  						<%= hidden_field_tag :followed_id, @user.id %>
  						<%= f.submit "Follow", class: "btn" %>
						<% end %>
   				<%end%>
 				<%end%>
	   	<%end%>
				</td>
			</tr>
			<tr>
				<td> Nombre</td> <td> <%= @user.nombre %> </td>
			</tr>
			<tr>
				<td> Apellido</td> <td><%= @user.apellido %> </td>
			</tr>
			<tr>
				<td> Email</td> <td><%= @user.email %> </td>
			</tr>
			<tr>
				<td> F. Nacimiento</td> <td><%= @user.nacimiento %> </td>
			</tr>
			<tr>
				<td> Descripcion</td> <td><%= @user.descripcion %> </td>
			</tr>
			<tr>
				<td> Rol</td> <td><%= @user.role %> </td>
			</tr>
		</tbody>
</table>

<% if logged_in? %>
	<% if @user.player? %>

		<!-- Usuarios que sigue -->
		<div class="row">
			<div class = "col s6">
				<div class="card gray z-depth-2">
					<div class="card-content">
						<span class="card-title">Sigue a</span>	
						<ul class="collection">
							<% if @user.following.empty? %>
								<li class="collection-item"> 
									No sigue a ningun usuario
								</li>
							<%else%>
								<% @user.following.each do |u| %>
									<li class="collection-item"> 
										<%= link_to u.nick, u %> 
										<%= link_to "Unfollow", "#", :class =>"btn secondary-content" %>
									 </li>
								 <%end%>
							<%end%>
						</ul>

						<div class="card-action">
							
						</div>			
					</div>
				</div>
			</div>
			<div class = "col s6">
				<div class="card gray z-depth-2">
					<div class="card-content">
						<span class="card-title">Seguidores</span>	
						<ul class="collection">
							<% if @user.followers.empty? %>
								<li class="collection-item"> 
									No posee seguidores
								</li>
							<%else%>
								<% @user.followers.each do |u| %>
									<li class="collection-item"> 
										<div> 
											<%= link_to u.nick, u %>
										</div>
									</li>
								<%end%>
							<%end%>
						</ul>

						<div class="card-action">
							
						</div>			
					</div>
				</div>
			</div>
		</div>


		<!-- Partidos que organiza y partidos en los que esta anotado -->
		<div class="row"> 
			<div class="col s6">
				<div class="card grey z-depth-2">
						<div class ="card-content">
							<span class="card-title">Partidos Organizados </span>
							<table class="responsive-table centered bordered white">
								<thead>
									<th> Local </th>
									<th> Cancha </th>
									<th> Fecha </th>
								</thead>
								<tbody>
									<% @user.partidos.each do |partido| %>
									<tr> 
										<td> <%= partido.local_id %> </td>
										<td> <%= partido.court_id %> </td>
										<td> <%= partido.fecha %> </td>
										<td> <%= link_to "Ver", partido, :class=>"btn" %> </td>
									</tr>
									<%end%>
								</tbody>
							</table>
						</div>
						
							<div class="card-action">
								<%= link_to 'Crear Partido', partidos_new_path, :class=>"btn" %>
							</div>
						
				</div>
			</div>


			<div class="col s6">
				<div class="card grey z-depth-2">
						<div class ="card-content">
							<span class="card-title">Anotado a </span>
							<table class="responsive-table centered bordered white">
								<thead>
									<th> Local </th>
									<th> Cancha </th>
									<th> Fecha </th>
								</thead>
								<tbody>
									<% @user.anotado_a.each do |partido| %>
									<tr> 
										<td> <%= partido.local_id %> </td>
										<td> <%= partido.court_id %> </td>
										<td> <%= partido.fecha %> </td>
										<td> <%= link_to "Ver", partido, :class=>"btn" %> </td>
									</tr>
									<%end%>
								</tbody>
							</table>
							
								<div class="card-action">
									<%= link_to 'Anotarse a uno', partidos_path, :class=>"btn" %>
								</div>
							
					</div>
				</div>
			</div>
		</div>

	<%else%>
		<!-- El usuario es local_owener -->
		<% local = Local.find_by(user_id: @user.id) %>
		<% unless local == nil %>
		  <div class="row">
				<h4 class="center z-depth-2 grey">Datos de Local</h4>

				<table class="centered highlight white z-depth-2" style="margin-bottom: 25px">
			
					<tbody>
						<tr>
							<td> Cancha</td> <td> <%= local.nombre %> </td>
						</tr>
						<tr>
							<td> Barrio</td> <td> <%= local.barrio %> </td>
						</tr>
						<tr>
							<td> Direccion</td> <td> <%= local.direccion %> </td>
						</tr>
						<tr>
							<td> Telefono</td> <td><%= local.telefono %> </td>
						</tr>
						<tr>
							<td> Email</td> <td><%= local.email %> </td>
						</tr>
						<tr>
							<td> Abierto</td> <td> <%= local.opens.strftime("%H:%M") %>Hs - <%= local.closes.strftime("%H:%M") %>Hs</td>
						</tr>
						
					</tbody>
				</table>
				<div class="row center">
					<%= link_to "Ver Local", local, :class=>"btn btn-large" %>
				</div>

			</div>	
		<%else%>
			<div class="row center">
				<%= link_to "Crear local", new_local_path, :class=>"btn btn-large" %>
			</div>
		<%end%>
	<%end%>
<%end%>
</div>