config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  
  get 'static_pages/home'

  get 'courts/new'
  get 'courts/create'
  get 'courts/destroy'
  
  get 'sessions/new'

  get 'anotados/index'
  get 'anotados/create'
  get 'anotados/new'
  get 'anotados/show'
  post 'anotados/aceptar'
  post 'anotados/quitar'

  get 'partidos/index'
  get 'partidos/show'
  get 'partidos/new'
  get 'partidos/create'

  get '/signup',  to: 'users#new'  
  get '/login',   to: 'sessions#new'
  get 'logout',   to: 'sessions#destroy'
  post  '/login', to: 'sessions#create'
  # get 'locals/canchas' to: 'locals#canchas'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :partidos do
    member do
      get :armar
    end
  end
  resources :anotados
  resources :relationships,  only: [:create, :destroy]
  
  resources :locals do
    member do
      get :canchas
    end
  end
  resources :courts, only: [:new, :create, :destroy]
end

app/models/anotado.rb
class Anotado < ApplicationRecord
	belongs_to :user
	belongs_to :partido
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/court.rb
class Court < ApplicationRecord
  belongs_to :local
end

app/models/court_type.rb
class CourtType < ActiveRecord::Base
  enum court_type: [:F5, :F7, :F11]
end

app/models/local.rb
class Local < ApplicationRecord
	has_many :courts
	belongs_to :user 
end

app/models/partido.rb
class Partido < ApplicationRecord
  NUMBER_OF_MAX_PLAYERS_SUBSCRIBED = 10
  belongs_to :user
  belongs_to :local
  has_many :anotados
  has_many :aceptados, -> {where(aceptado: true)}, :class_name => 'Anotado' #, before_add: :validates_players_limit

  
  private

  def validates_players_limit(aceptados)
  	raise Exception.new if aceptados.size >= NUMBER_OF_MAX_PLAYERS_SUBSCRIBED
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"

	validates :follower_id, presence: true
	validates :followed_id, presence: true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :court
  belongs_to :partido
end

app/models/user.rb
class User < ApplicationRecord
	#roles
	enum role: [:local_owner, :player]
	after_initialize :set_default_role, :if => :new_record?

	has_secure_password
	#relaciones con los partidos
	has_many :partidos #organiza muchos partidos
	has_many :anotados
	has_many :anotado_a, through: :anotados, source: :partido
	
	#relaciones con los usuarios
	has_many :active_relationships, class_name: "Relationship",
																foreign_key: "follower_id",
																dependent: :destroy
	has_many :passive_relationships, class_name:  "Relationship",
                                 foreign_key: "followed_id",
                                 dependent:   :destroy
	has_many :following, through: :active_relationships, source: :followed
	has_many :followers, through: :passive_relationships, source: :follower 


	before_save { self.nick = nick.downcase }
	validates :nick, 	presence: true, 
									 	length: {minimum: 5}, 		
									 	uniqueness: {case_sensitive: false}
	validates :password, presence: true,
											 length: { minimum: 6 }
	validates :email, presence: true,
										format: { with: /\A\w[\w\d]+@\w+.com/ },
										uniqueness: true
	validates :nombre, presence: true
	validates :apellido, presence: true
	validates :nacimiento, presence: true

	#imagenes
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/default_user.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

	#seguir usuarios

	def follow (other_user)
		following << other_user
	end

	def unfollow (other_user)
		following.delete(other_user)
	end

	def following?(other_user)
		following.include?(other_user)
	end

	#roles
	def set_default_role
    self.role ||= :player
  end

	private


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		if logged_in? and current_user.player?	
				@users = User.player
		else
			@users = User.all
		end
	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def edit
	end

	def create
		@user = User.new(user_params)
		if(@user.save)
			log_in @user
			redirect_to :action => 'show', :id => @user.id
		else
			render 'new'
		end
	end

	def update
	end

	def destroy
		
	end
	

	private
		
		def user_params
			params.require(:user).permit(	:nick, :password, 
																		:password_confirmation, 
																 		:nombre, :apellido, :nacimiento, :email, 
																 		:descripcion, :avatar, :role)
		end

end

app/helpers/anotados_helper.rb
module AnotadosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courts_helper.rb
module CourtsHelper
end

app/helpers/locals_helper.rb
module LocalsHelper
end

app/helpers/partidos_helper.rb
module PartidosHelper
end

app/helpers/ralationships_helper.rb
module RalationshipsHelper
end

app/helpers/reservation_helper.rb
module ReservationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def current_user?(other_user)
		@current_user.id == other_user.id
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fulbo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body class="green">
  	<header>
  		<%= render 'shared/header' %>
		</header>
		
    <div class="container">
      <%= yield %>
    </div>

    <footer class="page-footer green darken-3">
      <%= render 'shared/footer' %>
    </footer>
    <script type="text/javascript">
      $(document).ready(function() {
        $('select').material_select();
      });
    </script>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="container">
	<div class="footer-copyright">
    <div class="container">
     	2018 Copyright Text
    <a class="grey-text text-lighten-4 right" href="#!">Espartafilardo</a>
    </div>
  </div>
</div>

app/views/shared/_header.html.erb
<nav class="z-depth-5">
	<div class="nav-wrapper green darken-3">
		<ul class="left hide-on-med-and-down">
			<% if logged_in? %>
				<li> <%= link_to "Usuarios", users_path %></li>
				<li> <%= link_to "Partidos", partidos_path %></li>
			<%end%>
			<li> <%= link_to "Locales", locals_path %></li>
			<% if logged_in? %>
				<% if current_user.local_owner? %>
					<% if Local.find_by(user_id: current_user.id) == nil %>
						<li> <%= link_to "Nuevo Local", new_local_path %> </li>
					<%end%>
				<%end%>
			<%end%>	
		</ul>

		<%= link_to "Fulbo", root_path, {:class=>"brand-logo center"} %>

		<ul class="right">
			<li>
				<% if logged_in? %>
					<%= link_to current_user.nick, current_user, { :class => "right"} %>
					<%= link_to 'Cerrar Sesion', '/logout', { :class => "right"} %> 
				<% else %>
						<%= link_to 'Iniciar Sesion', '/login', { :class => "right"} %>
						<%= link_to 'Registrarse', '/signup', { :class => "right"} %> 
				<% end %>
			</li>		
		</ul>
	</div>
</nav>